### ISSUE TITLE
exclude records with AC==0 in single_cohort_munge_variantlist

### ISSUE THREAD

**Issue by andrei-barysenka** [hmgu-itg/burden_testing#10]
imputed data can have those

**Comment by youngchanpark** [comment]
Hi Andrei,

I noticed this too, although I didn't know it was because my data was because of imputed data.

 I talked to Arthur about it and so I added a line
`d=d[ac>0,]` to the `single_cohort_munge_variantlist` script. 

Commit link below. 

https://github.com/hmgu-itg/burden_testing/commit/e07cd4204970e6656b9234d16165b8675212a4ce


Will close the issue :)
